name: Quality Check & Release

on:
  push:
    branches: [main, beta]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint files
        run: yarn lint

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Perform type checking
        run: yarn lint:types

  publish:
    name: Release
    needs: [lint, type-check]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Semantic release
        run: npx semantic-release@19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
